### ISSUE TITLE
option for partial saving of entities with unserializable components?

### ISSUE THREAD

**Issue by rydb** [Zeenobit/moonshine_save#16] opened 2024-12-04 23:01 UTC
I use this library as a backend for my library, bevy_serialziation_extras
https://github.com/rydb/bevy_serialization_extras

and an issue I'm currently facing is that some components do not implement reflect, but the components are not critical enough to warrant breaking saving, but they do currently break it do to moonshine's default behaviour to not save/load on encountering non-reflecting/non-registered components in entities.

With the introduction of required components in 0.15, would it be possible for moonshine save to get a "partial save mode" where you can set it to just emit warnings on invalid components instead of breaking the save process?

 E.G: I do not care that misc helper camera components(`CameraMainTextureUsages`) from bevy don't serialize, because spawning `Camera3d` will automatically spawn the default variants of those. I'd like to fix it later maybe, but it makes porting to new versions of bevy more painful.

**Comment by Zeenobit** [comment] 2024-12-04 23:24
You can already do this by excluding components from save data. See [`exclude_component`](https://docs.rs/moonshine-save/latest/moonshine_save/save/struct.SavePipelineBuilder.html#method.exclude_component).

Unfortunately, this does mean you need to manually exclude every unserializable component. I'm not aware of any other way to do this with Bevy's built in Dynamic Scene builder, but I'll investigate.

For now, let me know if `exclude_component` works for your case :)

**Comment by rydb** [comment] 2024-12-05 00:07
> You can already do this by excluding components from save data. See [`exclude_component`](https://docs.rs/moonshine-save/latest/moonshine_save/save/struct.SavePipelineBuilder.html#method.exclude_component).
> 
> Unfortunately, this does mean you need to manually exclude every unserializable component. I'm not aware of any other way to do this with Bevy's built in Dynamic Scene builder, but I'll investigate.

Thank you, if it isn't possible, maybe 0.16 will have something for us 😢

> For now, let me know if `exclude_component` works for your case :)

It does, as manual as it is...

**Comment by Zeenobit** [comment] 2024-12-05 02:45
What is the specific error/panic you're getting? And is this during load or save?

**Comment by rydb** [comment] 2024-12-06 21:47
> What is the specific error/panic you're getting? And is this during load or save?
```rust
moonshine_save::save: save failed: Ron(Message("type `core::ops::Range<f32>` did not register the `ReflectSerialize` or `ReflectSerializeWithRegistry` type data. For certain types, this may need to be registered manually using `register_type_data` (stack: `bevy_render::view::ColorGrading` -> `bevy_render::view::ColorGradingGlobal` -> `core::ops::Range<f32>`)"))
```
I can quickly fix it with
```rust
        .register_type::<Range<f32>>()
        .register_type_data::<Range<f32>, ReflectSerialize>()
        .register_type_data::<Range<f32>, ReflectDeserialize>()
```
but it means anything I don't immediately catch when im doing testing in test worlds will cause users to need to add their type's variation of fix them selves.

**Comment by Zeenobit** [comment] 2024-12-06 22:38
I wonder if this should be fixed on Bevy side. `Range<f32>` is a pretty fundamental type, so I'd expect it to be serializable.

And this is why I asked my original question. Cause \*saving\* should be ok even if entities have unserializable components. Components like `ColorGrading` should be serializable though since it doesn't seem like it has any dynamic data.

**Comment by rydb** [comment] 2024-12-07 00:38
> What is the specific error/panic you're getting? And is this during load or save?
```rust
moonshine_save::save: save failed: Ron(Message("type `core::ops::Range<f32>` did not register the `ReflectSerialize` or `ReflectSerializeWithRegistry` type data. For certain types, this may need to be registered manually using `register_type_data` (stack: `bevy_render::view::ColorGrading` -> `bevy_render::view::ColorGradingGlobal` -> `core::ops::Range<f32>`)"))
```
I can quickly fix it with
```rust
        .register_type::<Range<f32>>()
        .register_type_data::<Range<f32>, ReflectSerialize>()
        .register_type_data::<Range<f32>, ReflectDeserialize>()
```
but it means anything I don't immediately catch when im doing testing in test worlds will cause users to need to add their type's variation of fix them selves.

**Comment by rydb** [comment] 2024-12-07 00:41
> I wonder if this should be fixed on Bevy side. `Range<f32>` is a pretty fundamental type, so I'd expect it to be serializable.
> 
> And this is why I asked my original question. Cause *saving* should be ok even if entities have unserializable components. Components like `ColorGrading` should be serializable though since it doesn't seem like it has any dynamic data.

well.. it currently isn't.

I've got a pretty gnarly list of .register_type(s) that comes prepackaged in the plugin from manual testing due to this limitation. This list is only gonna grow larger unless fix gets put to bevy if this is a bevy issue...

```rust
        .register_type::<[f32; 3]>()
        .register_type::<AlphaMode>()
        .register_type::<ParallaxMappingMethod>()
        .register_type::<Camera3dDepthTextureUsage>()
        .register_type::<InheritedVisibility>()
        .register_type::<ScreenSpaceTransmissionQuality>()
        .register_type::<GeometryFile>()
        .register_type::<MeshPrimitive>()
        .register_type::<GeometryFlag>()
        .register_type::<[[f32; 3]; 3]>()
        .register_type::<[Vec3; 3]>()
        .register_type::<CameraRenderGraph>()
        .register_type::<CameraMainTextureUsages>()
        .register_type::<TypeRegistryOnSave>()
        .register_type::<LoadRequest>()
        .register_type::<SaveRequest>()
        .register_type::<ComponentsOnSave>()
        .register_type::<ShowSerializable>()
        .register_type::<ShowUnserializable>()
        .register_type::<Range<f32>>()
        ```

**Comment by Zeenobit** [comment] 2024-12-07 02:52
To me, stuff like arrays and `Range` should be supported by Bevy native:
```rust
.register_type::<[f32; 3]>()
.register_type::<[[f32; 3]; 3]>()
.register_type::<[Vec3; 3]>()
.register_type::<Range<f32>>()
```
Not being able to serialize `Range` and arrays sounds like an oversight, or just a missing feature (for arrays). I think this is the root cause of your issue.

As for these components,
```rust
.register_type::<AlphaMode>()
.register_type::<ParallaxMappingMethod>()
.register_type::<Camera3dDepthTextureUsage>()
.register_type::<InheritedVisibility>()
.register_type::<ScreenSpaceTransmissionQuality>()
.register_type::<GeometryFile>()
.register_type::<MeshPrimitive>()
.register_type::<GeometryFlag>()
.register_type::<CameraRenderGraph>()
.register_type::<CameraMainTextureUsages>()
```
I'm not sure why you'd need to register things like `InheritedVisibility`. With required components, these should be auto-inserted on load, no?

As for others, they should be split into two groups:
- Serializable: These are unregistered components with serializable data (e.g. `Camera3dDepthTextureUsage` or `ScreenSpaceTransmissionQuality`).
    - These should be registered by Bevy. If you have them on a saved entity, I'm not sure why you'd ever NOT want to save them.
    - Even if these components aren't registered, they shouldn't be preventing you from saving or loading. They just wouldn't get saved. So I'm not sure why you NEED to register them.
- Non-Serializable: Anything with dynamic data (e.g. anything with a `Box` member like `CameraRenderGraph`).
    - These are just not serializable. So again, I'm not sure why you'd need to register them. If they're not registered, they would just get stripped from Saved entities on save (or at least they should!)
    - If they are registered, for whatever reason, you need to explicitly use `exclude_component` to exclude them or `map_component` to map them before save/load. There is really no way for moonshine to know which one of these components should be excluded from the saved data to do a "partial save".

Also, I'm not sure why you'd be saving/loading the save/load requests. That seems like opening a case for infinite recursion!
```rust
.register_type::<LoadRequest>()
.register_type::<SaveRequest>()
```

**Closed** 2024-12-18 03:18 UTC
